# Generated by Django 5.0.6 on 2024-07-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
